### ISSUE TITLE
Request for a name change

### ISSUE THREAD

**Issue by joehakimrahme** [omaraboumrad/mastool#10]
The word mastool (مسطول) has a very negative connotation in my language as it means "idiot".
Would it be possible to rename it to something a bit more welcoming?

How about something like helpfulTool? kthxbai

**Comment by ghost** [comment]
I would prefer "powerTool", since it's more empowering than "helpfulTool".
Also, we don't completely lose mastool's admittedly clever play on words so... there's that :+1:

**Comment by omaraboumrad** [comment]
We thank you for your concerns and promise to bring it up in the next board meeting. Such a major change requires a significant amount of money and anything beyond 50 cents is considered capital expenditure and requires the approval of many.

We expect the process to take a few years. :-)
